version: "3.7"

services:
  wplt:
    image: wplt
    container_name: wplt
    environment:
      - SECRET_KEY=CHANGETHIS
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - wplt
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  wplt:
    name: wplt
    driver: bridge
