version: "3.7"

services:
  wplt:
    image: znibb/wplt:latest
    container_name: wplt
    environment:
      - SECRET_KEY=CHANGETHIS
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - wplt
    ports:
      - "5000:5000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_wplt
    environment:
      - "WATCHTOWER_LABEL_ENABLE=true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - wplt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable

networks:
  wplt:
    name: wplt
    driver: bridge
